// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20250107210906_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Magacin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDostave")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int?>("MaterijalId")
                        .HasColumnType("int");

                    b.Property<int?>("StovaristeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterijalId");

                    b.HasIndex("StovaristeId");

                    b.ToTable("Magacin");
                });

            modelBuilder.Entity("WebTemplate.Models.Materijal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Cena")
                        .HasColumnType("float");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivProizvodjaca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sifra")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Materijal");
                });

            modelBuilder.Entity("WebTemplate.Models.Stovariste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stovariste");
                });

            modelBuilder.Entity("WebTemplate.Models.Magacin", b =>
                {
                    b.HasOne("WebTemplate.Models.Materijal", "Materijal")
                        .WithMany("Magacin")
                        .HasForeignKey("MaterijalId");

                    b.HasOne("WebTemplate.Models.Stovariste", "Stovariste")
                        .WithMany("Magacin")
                        .HasForeignKey("StovaristeId");

                    b.Navigation("Materijal");

                    b.Navigation("Stovariste");
                });

            modelBuilder.Entity("WebTemplate.Models.Materijal", b =>
                {
                    b.Navigation("Magacin");
                });

            modelBuilder.Entity("WebTemplate.Models.Stovariste", b =>
                {
                    b.Navigation("Magacin");
                });
#pragma warning restore 612, 618
        }
    }
}
