// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    partial class IspitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Rezervoar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FrekvencijaCiscenja")
                        .HasColumnType("int");

                    b.Property<float>("Kapacitet")
                        .HasColumnType("real");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VremePoslednjegCiscenja")
                        .HasColumnType("datetime2");

                    b.Property<float>("Zapremina")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Rezervoar");
                });

            modelBuilder.Entity("WebTemplate.Models.Riba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GodineStarosti")
                        .HasColumnType("int");

                    b.Property<float>("Masa")
                        .HasColumnType("real");

                    b.Property<string>("Vrsta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Riba");
                });

            modelBuilder.Entity("WebTemplate.Models.UbaciRibu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDodavanja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RezervoarId")
                        .HasColumnType("int");

                    b.Property<int?>("RibaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RezervoarId");

                    b.HasIndex("RibaId");

                    b.ToTable("UbaciRibu");
                });

            modelBuilder.Entity("WebTemplate.Models.UbaciRibu", b =>
                {
                    b.HasOne("WebTemplate.Models.Rezervoar", "Rezervoar")
                        .WithMany("ubaciRibe")
                        .HasForeignKey("RezervoarId");

                    b.HasOne("WebTemplate.Models.Riba", "Riba")
                        .WithMany("UbaciRibu")
                        .HasForeignKey("RibaId");

                    b.Navigation("Rezervoar");

                    b.Navigation("Riba");
                });

            modelBuilder.Entity("WebTemplate.Models.Rezervoar", b =>
                {
                    b.Navigation("ubaciRibe");
                });

            modelBuilder.Entity("WebTemplate.Models.Riba", b =>
                {
                    b.Navigation("UbaciRibu");
                });
#pragma warning restore 612, 618
        }
    }
}
